### // SEARCH ALL GAMES
GET  http://localhost:3001/games 

### // SEARCH GAME NAME
GET  http://localhost:3001/games?name=limb

### // SEARCH GAME ID
GET  http://localhost:3001/games/3328

### // SEARCH ALL GENRES
GET  http://localhost:3001/genres